<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bills.proto

namespace Protobuf\Business\Bills;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * 账单列表响应体
 * </pre>
 *
 * Protobuf type <code>protobuf.business.bills.BillListResponse</code>
 */
class BillListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 开始日期 
     * </pre>
     *
     * <code>string startDate = 1;</code>
     */
    private $startDate = '';
    /**
     * <pre>
     * 结束日期
     * </pre>
     *
     * <code>string endDate = 2;</code>
     */
    private $endDate = '';
    /**
     * <pre>
     * 门店账单
     * </pre>
     *
     * <code>repeated .protobuf.business.bills.MerchantBill merchantBill = 3;</code>
     */
    private $merchantBill;

    public function __construct() {
        \GPBMetadata\Bills::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 开始日期 
     * </pre>
     *
     * <code>string startDate = 1;</code>
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * <pre>
     * 开始日期 
     * </pre>
     *
     * <code>string startDate = 1;</code>
     */
    public function setStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->startDate = $var;
    }

    /**
     * <pre>
     * 结束日期
     * </pre>
     *
     * <code>string endDate = 2;</code>
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * <pre>
     * 结束日期
     * </pre>
     *
     * <code>string endDate = 2;</code>
     */
    public function setEndDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->endDate = $var;
    }

    /**
     * <pre>
     * 门店账单
     * </pre>
     *
     * <code>repeated .protobuf.business.bills.MerchantBill merchantBill = 3;</code>
     */
    public function getMerchantBill()
    {
        return $this->merchantBill;
    }

    /**
     * <pre>
     * 门店账单
     * </pre>
     *
     * <code>repeated .protobuf.business.bills.MerchantBill merchantBill = 3;</code>
     */
    public function setMerchantBill(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protobuf\Business\Bills\MerchantBill::class);
        $this->merchantBill = $arr;
    }

}

