<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bills.proto

namespace Protobuf\Business\Bills;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * 账单列表结构体
 * </pre>
 *
 * Protobuf type <code>protobuf.business.bills.BillListRequest</code>
 */
class BillListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * 开始日期
     * </pre>
     *
     * <code>string startDate = 1;</code>
     */
    private $startDate = '';
    /**
     * <pre>
     * 结束日期
     * </pre>
     *
     * <code>string endDate = 2;</code>
     */
    private $endDate = '';
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int32 wuid = 3;</code>
     */
    private $wuid = 0;
    /**
     * <pre>
     * 门店ID
     * </pre>
     *
     * <code>int32 meid = 4;</code>
     */
    private $meid = 0;
    /**
     * <pre>
     * 品牌ID
     * </pre>
     *
     * <code>int32 bid = 5;</code>
     */
    private $bid = 0;

    public function __construct() {
        \GPBMetadata\Bills::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * 开始日期
     * </pre>
     *
     * <code>string startDate = 1;</code>
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * <pre>
     * 开始日期
     * </pre>
     *
     * <code>string startDate = 1;</code>
     */
    public function setStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->startDate = $var;
    }

    /**
     * <pre>
     * 结束日期
     * </pre>
     *
     * <code>string endDate = 2;</code>
     */
    public function getEndDate()
    {
        return $this->endDate;
    }

    /**
     * <pre>
     * 结束日期
     * </pre>
     *
     * <code>string endDate = 2;</code>
     */
    public function setEndDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->endDate = $var;
    }

    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int32 wuid = 3;</code>
     */
    public function getWuid()
    {
        return $this->wuid;
    }

    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int32 wuid = 3;</code>
     */
    public function setWuid($var)
    {
        GPBUtil::checkInt32($var);
        $this->wuid = $var;
    }

    /**
     * <pre>
     * 门店ID
     * </pre>
     *
     * <code>int32 meid = 4;</code>
     */
    public function getMeid()
    {
        return $this->meid;
    }

    /**
     * <pre>
     * 门店ID
     * </pre>
     *
     * <code>int32 meid = 4;</code>
     */
    public function setMeid($var)
    {
        GPBUtil::checkInt32($var);
        $this->meid = $var;
    }

    /**
     * <pre>
     * 品牌ID
     * </pre>
     *
     * <code>int32 bid = 5;</code>
     */
    public function getBid()
    {
        return $this->bid;
    }

    /**
     * <pre>
     * 品牌ID
     * </pre>
     *
     * <code>int32 bid = 5;</code>
     */
    public function setBid($var)
    {
        GPBUtil::checkInt32($var);
        $this->bid = $var;
    }

}

