<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bills.proto

namespace Protobuf\Business\Bills;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * 门店账单结构
 * </pre>
 *
 * Protobuf type <code>protobuf.business.bills.MerchantBill</code>
 */
class MerchantBill extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <pre>
     * 结算金额
     * </pre>
     *
     * <code>int32 settlementAmount = 2;</code>
     */
    private $settlementAmount = 0;
    /**
     * <pre>
     * 结算笔数
     * </pre>
     *
     * <code>int32 settlementCount = 3;</code>
     */
    private $settlementCount = 0;
    /**
     * <pre>
     * 实收金额
     * </pre>
     *
     * <code>int32 actualAmount = 4;</code>
     */
    private $actualAmount = 0;
    /**
     * <pre>
     * 实收笔数
     * </pre>
     *
     * <code>int32 actualCount = 5;</code>
     */
    private $actualCount = 0;
    /**
     * <pre>
     * 应收金额
     * </pre>
     *
     * <code>int32 receivableAmount = 6;</code>
     */
    private $receivableAmount = 0;
    /**
     * <pre>
     * 应收笔数
     * </pre>
     *
     * <code>int32 receivableCount = 7;</code>
     */
    private $receivableCount = 0;
    /**
     * <pre>
     * 退款金额
     * </pre>
     *
     * <code>int32 refundAmount = 8;</code>
     */
    private $refundAmount = 0;
    /**
     * <pre>
     * 退款笔数
     * </pre>
     *
     * <code>int32 refundCount = 9;</code>
     */
    private $refundCount = 0;
    /**
     * <pre>
     * 商家优惠金额
     * </pre>
     *
     * <code>int32 merchantCouponAmount = 10;</code>
     */
    private $merchantCouponAmount = 0;
    /**
     * <pre>
     * 商家优惠笔数
     * </pre>
     *
     * <code>int32 merchantCouponCount = 11;</code>
     */
    private $merchantCouponCount = 0;
    /**
     * <pre>
     * 手续费
     * </pre>
     *
     * <code>int32 commission = 12;</code>
     */
    private $commission = 0;
    /**
     * <pre>
     * 商户ID
     * </pre>
     *
     * <code>int32 meid = 13;</code>
     */
    private $meid = 0;

    public function __construct() {
        \GPBMetadata\Bills::initOnce();
        parent::__construct();
    }

    /**
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     * 结算金额
     * </pre>
     *
     * <code>int32 settlementAmount = 2;</code>
     */
    public function getSettlementAmount()
    {
        return $this->settlementAmount;
    }

    /**
     * <pre>
     * 结算金额
     * </pre>
     *
     * <code>int32 settlementAmount = 2;</code>
     */
    public function setSettlementAmount($var)
    {
        GPBUtil::checkInt32($var);
        $this->settlementAmount = $var;
    }

    /**
     * <pre>
     * 结算笔数
     * </pre>
     *
     * <code>int32 settlementCount = 3;</code>
     */
    public function getSettlementCount()
    {
        return $this->settlementCount;
    }

    /**
     * <pre>
     * 结算笔数
     * </pre>
     *
     * <code>int32 settlementCount = 3;</code>
     */
    public function setSettlementCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->settlementCount = $var;
    }

    /**
     * <pre>
     * 实收金额
     * </pre>
     *
     * <code>int32 actualAmount = 4;</code>
     */
    public function getActualAmount()
    {
        return $this->actualAmount;
    }

    /**
     * <pre>
     * 实收金额
     * </pre>
     *
     * <code>int32 actualAmount = 4;</code>
     */
    public function setActualAmount($var)
    {
        GPBUtil::checkInt32($var);
        $this->actualAmount = $var;
    }

    /**
     * <pre>
     * 实收笔数
     * </pre>
     *
     * <code>int32 actualCount = 5;</code>
     */
    public function getActualCount()
    {
        return $this->actualCount;
    }

    /**
     * <pre>
     * 实收笔数
     * </pre>
     *
     * <code>int32 actualCount = 5;</code>
     */
    public function setActualCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->actualCount = $var;
    }

    /**
     * <pre>
     * 应收金额
     * </pre>
     *
     * <code>int32 receivableAmount = 6;</code>
     */
    public function getReceivableAmount()
    {
        return $this->receivableAmount;
    }

    /**
     * <pre>
     * 应收金额
     * </pre>
     *
     * <code>int32 receivableAmount = 6;</code>
     */
    public function setReceivableAmount($var)
    {
        GPBUtil::checkInt32($var);
        $this->receivableAmount = $var;
    }

    /**
     * <pre>
     * 应收笔数
     * </pre>
     *
     * <code>int32 receivableCount = 7;</code>
     */
    public function getReceivableCount()
    {
        return $this->receivableCount;
    }

    /**
     * <pre>
     * 应收笔数
     * </pre>
     *
     * <code>int32 receivableCount = 7;</code>
     */
    public function setReceivableCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->receivableCount = $var;
    }

    /**
     * <pre>
     * 退款金额
     * </pre>
     *
     * <code>int32 refundAmount = 8;</code>
     */
    public function getRefundAmount()
    {
        return $this->refundAmount;
    }

    /**
     * <pre>
     * 退款金额
     * </pre>
     *
     * <code>int32 refundAmount = 8;</code>
     */
    public function setRefundAmount($var)
    {
        GPBUtil::checkInt32($var);
        $this->refundAmount = $var;
    }

    /**
     * <pre>
     * 退款笔数
     * </pre>
     *
     * <code>int32 refundCount = 9;</code>
     */
    public function getRefundCount()
    {
        return $this->refundCount;
    }

    /**
     * <pre>
     * 退款笔数
     * </pre>
     *
     * <code>int32 refundCount = 9;</code>
     */
    public function setRefundCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->refundCount = $var;
    }

    /**
     * <pre>
     * 商家优惠金额
     * </pre>
     *
     * <code>int32 merchantCouponAmount = 10;</code>
     */
    public function getMerchantCouponAmount()
    {
        return $this->merchantCouponAmount;
    }

    /**
     * <pre>
     * 商家优惠金额
     * </pre>
     *
     * <code>int32 merchantCouponAmount = 10;</code>
     */
    public function setMerchantCouponAmount($var)
    {
        GPBUtil::checkInt32($var);
        $this->merchantCouponAmount = $var;
    }

    /**
     * <pre>
     * 商家优惠笔数
     * </pre>
     *
     * <code>int32 merchantCouponCount = 11;</code>
     */
    public function getMerchantCouponCount()
    {
        return $this->merchantCouponCount;
    }

    /**
     * <pre>
     * 商家优惠笔数
     * </pre>
     *
     * <code>int32 merchantCouponCount = 11;</code>
     */
    public function setMerchantCouponCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->merchantCouponCount = $var;
    }

    /**
     * <pre>
     * 手续费
     * </pre>
     *
     * <code>int32 commission = 12;</code>
     */
    public function getCommission()
    {
        return $this->commission;
    }

    /**
     * <pre>
     * 手续费
     * </pre>
     *
     * <code>int32 commission = 12;</code>
     */
    public function setCommission($var)
    {
        GPBUtil::checkInt32($var);
        $this->commission = $var;
    }

    /**
     * <pre>
     * 商户ID
     * </pre>
     *
     * <code>int32 meid = 13;</code>
     */
    public function getMeid()
    {
        return $this->meid;
    }

    /**
     * <pre>
     * 商户ID
     * </pre>
     *
     * <code>int32 meid = 13;</code>
     */
    public function setMeid($var)
    {
        GPBUtil::checkInt32($var);
        $this->meid = $var;
    }

}

